### ISSUE TITLE
name clashes, suggest prefixing

### ISSUE THREAD

**Issue by larshp** [victorizbitskiy/zconcurrency_api#1]
Hi,
dotabap.org will [daily check](https://github.com/dotabap/dotabap-list/runs/1679948535) for name clashes between repositories, following names overlap with https://github.com/SchwarzIT/abap_oo_patterns

```
zcl_collection.clas.abap
zcl_collection.clas.xml
zcl_iterator.clas.abap
zcl_iterator.clas.xml
zif_collection.intf.abap
zif_collection.intf.xml
zif_iterator.intf.abap
zif_iterator.intf.xml
```

Suggest that you prefix object names, eg. `zcl_capi_collection.clas.abap`

I have opened the corresponding issue in https://github.com/SchwarzIT/abap_oo_patterns/issues/3

**Comment by victorizbitskiy** [comment]
Hi Lars! 
I have added CAPI prefix to class and interfaces names.
Thank you for the suggestion
