### ISSUE TITLE
Lack of documentation: use cases, sequence diagrams, etc.

### ISSUE THREAD

**Issue by ilyakaznacheev** [victorizbitskiy/zconcurrency_api#2]
Great tool, but not clear how to use it.

It would be great to have some basic explanation, which kind of problems may be solved by means of this. At least to start with and to decide either I need to use id or search for another solution.

Some sequence diagrams of what is executed in which order would improve documentation too.

**Comment by victorizbitskiy** [comment]
@ilyakaznacheev, I added a description in Russian and English. The English description probably contains many grammatical errors. I can't fix them until I learn English...😅
